-- ── PERFUME GALLERY — Supabase Setup ──────────────────────────
-- Run this entire file in Supabase → SQL Editor → New Query

-- 1. PRODUCTS TABLE
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text default 'PG EXCLUSIVE',
  price numeric not null,
  size text,
  description text,
  category text default 'Oud',
  stock integer default 0,
  image_url text,
  created_at timestamp with time zone default now()
);

-- 2. ORDERS TABLE
create table if not exists orders (
  id text primary key,
  customer text not null,
  contact text not null,
  method text not null,
  items jsonb not null,
  total numeric not null,
  status text default 'Pending',
  date text,
  created_at timestamp with time zone default now()
);

-- 3. ENABLE ROW LEVEL SECURITY
alter table products enable row level security;
alter table orders enable row level security;

-- 4. POLICIES — allow public read on products
create policy "Public can view products"
  on products for select
  using (true);

-- allow public to insert orders (customers placing orders)
create policy "Public can place orders"
  on orders for insert
  with check (true);

-- allow public to read orders (admin uses anon key)
create policy "Public can view orders"
  on orders for select
  using (true);

-- allow public to update orders (admin updates status)
create policy "Public can update orders"
  on orders for update
  using (true);

-- allow public to insert products (admin uses anon key)
create policy "Public can insert products"
  on products for insert
  with check (true);

-- allow public to update products
create policy "Public can update products"
  on products for update
  using (true);

-- allow public to delete products
create policy "Public can delete products"
  on products for delete
  using (true);

-- 5. STORAGE BUCKET for product images
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- allow public to upload images
create policy "Public can upload images"
  on storage.objects for insert
  with check (bucket_id = 'product-images');

-- allow public to view images
create policy "Public can view images"
  on storage.objects for select
  using (bucket_id = 'product-images');

-- allow public to delete images
create policy "Public can delete images"
  on storage.objects for delete
  using (bucket_id = 'product-images');

-- 6. SAMPLE PRODUCTS (optional — delete if you want to start fresh)
insert into products (name, brand, price, size, description, category, stock, image_url) values
  ('Oud Noir', 'PG EXCLUSIVE', 45000, '100ml', 'A deep, smoky oud blended with amber and vetiver. The signature of power.', 'Oud', 12, 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=85&fit=crop'),
  ('Rose Impériale', 'PG EXCLUSIVE', 38000, '75ml', 'Bulgarian rose heart with a whisper of musk and sandalwood.', 'Floral', 8, 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&q=85&fit=crop'),
  ('Amber Soleil', 'PG EXCLUSIVE', 52000, '100ml', 'Warm amber, benzoin and golden vanilla — sunlight in a bottle.', 'Oriental', 5, 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&q=85&fit=crop'),
  ('Vetiver Brut', 'PG EXCLUSIVE', 41000, '50ml', 'Raw earth, green vetiver and cedarwood. Uncompromisingly bold.', 'Woody', 15, 'https://images.unsplash.com/photo-1592945403407-9caf930b5f80?w=600&q=85&fit=crop'),
  ('Jasmine Nocturne', 'PG EXCLUSIVE', 35000, '75ml', 'Night-blooming jasmine with soft iris and white musk drydown.', 'Floral', 20, 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&q=85&fit=crop'),
  ('Saffron King', 'PG EXCLUSIVE', 65000, '100ml', 'Precious saffron, leather and labdanum. Worn by those who know.', 'Oriental', 3, 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=85&fit=crop')
on conflict do nothing;
